import { Bell, BellRing, Megaphone } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AdminLayout } from '../../layouts/AdminLayout.jsx';
import { StatCard } from '../../components/admin/StatCard.jsx';
import { adminService } from '../../services/adminService.js';

export function NotificationsPage() {
  const [stats, setStats] = useState(null);

  useEffect(() => {
    adminService.notificationStats().then(setStats);
  }, []);

  return (
    <AdminLayout title="Notifications">
      <p className="-mt-4 mb-6 max-w-xl text-sm text-on-surface-variant">Platform-wide notification activity generated by service events.</p>

      <div className="grid gap-4 md:grid-cols-3">
        <StatCard icon={Bell} label="Total Sent" value={stats?.total ?? '—'} />
        <StatCard icon={BellRing} label="Unread" value={stats?.unread ?? '—'} iconBg="bg-warning/10" iconColor="text-warning" />
        <StatCard icon={Bell} label="Read Rate" value={stats ? `${stats.readRate}%` : '—'} iconBg="bg-success/10" iconColor="text-success" />
      </div>

      <section className="mt-6 rounded-lg border border-dashed border-outline-variant bg-surface-container-lowest p-8 text-center">
        <span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-secondary text-on-secondary">
          <Megaphone className="h-6 w-6" />
        </span>
        <h2 className="mt-4 font-headline text-lg font-bold">Broadcast messaging is not wired up yet</h2>
        <p className="mx-auto mt-2 max-w-md text-sm text-on-surface-variant">
          Notifications today are generated automatically by platform events (assignments, reviews, status changes). There is no
          backend endpoint yet for admins to send a manual broadcast to all users or artisans.
        </p>
      </section>
    </AdminLayout>
  );
}
